db.options:
  driver: 'pdo_mysql'
  charset: 'UTF8'
  master:
      user: 'root'
      password: 'root'
      host: 'localhost'
      dbname: 'achtkarspelen'
  slaves:
    0:
      user: 'root'
      password: 'root'
      host: 'localhost'
      dbname: 'achtkarspelen'
  wrapperClass: 'Doctrine\DBAL\Connections\MasterSlaveConnection'

orm.proxies_dir: '%app_path%/app/cache/Doctrine/Proxies'
orm.default_cache: 'apc' #should be set to apc/xcache on production
orm.em.options:
  mappings:
    0:
      type: 'annotation'
      namespace: 'MJanssen\Doctrine\Entity'
      alias: 'core'
      path: '%app_path%/src/MJanssen/Doctrine/Entity'
      use_simple_annotation_reader: false

base.url: ''

hmac_key: 'tempKey'
