validator:
  class: Silex\Provider\ValidatorServiceProvider

service.controller.service:
  class: Silex\Provider\ServiceControllerServiceProvider

doctrine.dbal:
  class: Silex\Provider\DoctrineServiceProvider

doctrine.orm:
  class: Dflydev\Silex\Provider\DoctrineOrm\DoctrineOrmServiceProvider

custom:
  class: MJanssen\Provider\ServiceProvider